MMCWeb/Controllers/EducationController.cs
using System.Web.Mvc;


// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace MMCWeb.controller
{
    public class EducationController : Controller
    {
        // GET: /<controller>/
        public ActionResult Index()
        {
            ViewBag.navInfo = "nav_med_education";
            return View();
        }
        public ActionResult Accreditation()
        {
            ViewBag.navInfo = "nav_med_education";
            return View();
        }
        public ActionResult EntryRequirement()
        {
            ViewBag.navInfo = "nav_med_education";
            return View();
        }
    }
}

MMCWeb/Controllers/InformationController.cs
using System.Web.Mvc;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace MMCWeb.controller
{
    public class InformationController : Controller
    {
        // GET: /<controller>/
        public ActionResult Index()
        {
            ViewBag.navInfo = "nav_information";
            return View();
        }
        public ActionResult Arbitration()
        {
            ViewBag.navInfo = "nav_information";
            return View();
        }
        public ActionResult Goodstanding()
        {
            ViewBag.navInfo = "nav_information";
            return View();
        }
        public ActionResult Recognition()
        {
            ViewBag.navInfo = "nav_information";
            return View();
        }
        public ActionResult Licencing()
        {
            ViewBag.navInfo = "nav_information";
            return View();
        }
        public ActionResult Registration()
        {
            ViewBag.navInfo = "nav_information";
            return View();
        }
        public ActionResult Relationship()
        {
            ViewBag.navInfo = "nav_information";
            return View();
        }
    }
}

MMCWeb/Controllers/RenewalApplicationController.cs
using Core.Interfaces;
using Data.Models;
using Infra.Repository;
using System;
using System.Web.Mvc;
using System.Linq;
using MMCWeb.Models;
using MMCWeb.Services;
// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace MMCWeb.controller
{
    public class RenewalApplicationController : Controller
    {
        private IUserMailer _userMailer;
        public IUserMailer UserMailer
        {
            get { return _userMailer; }
            set { _userMailer = value; }
        }
       // IRepository<tbRenewalPractitionerApplication> _renewalRepo;
        GovernmentDbContext _dbContext;
        public RenewalApplicationController()
        {
            _userMailer = new UserMailer();
            _dbContext = new GovernmentDbContext();
           // _renewalRepo = new Repository<tbRenewalPractitionerApplication>(_dbContext);
        }
        // GET: /<controller>/
      
        //public ActionResult ConfirmationInfo()
        //{
        //    var obj = _renewalRepo.Query(a => a.IsDeleted != true).FirstOrDefault();
        //    RenewalApplicationEmailInfo info = new RenewalApplicationEmailInfo()
        //    {
        //        Accesstime = obj.Accesstime,
        //        Name = obj.Name,
        //        Code = obj.Code,
        //        CurrentAddress = obj.CurrentAddress,
        //        Degree = obj.Degree,
        //        Email = obj.Email,
        //        GraduationYear = obj.GraduationYear,
        //        Township = obj.Township,
        //        StateDivision = obj.StateDivision,
        //        NRC = obj.NRC
        //    };
        //    return View(info);
        //}
        public ActionResult Status()
        {
            return View();
        }
        public ActionResult New()
        {
            ViewBag.navInfo = "nav_new";
            return View();
        }

        public ActionResult SendConfirmationInfo(string button, int id)
        {
            //if (button == "send")
            //{
            //    var obj = _renewalRepo.Query(a => a.ID == id && a.Source == "ONLINE" && a.IsDeleted != true).FirstOrDefault();
            //    if (obj != null)
            //    {
            //        SendEmail(obj);
            //        return PartialView("_View", obj);
            //    }
            //    return Json("Error!", JsonRequestBehavior.AllowGet);
            //}
            //else
            //{
                return Json("Redirect", JsonRequestBehavior.AllowGet);
            //}
        }
        //public void SendEmail(tbRenewalPractitionerApplication obj)
        public void SendEmail()
        {
            //UserMailer.SendEmail(new RenewalApplicationEmailInfo()
            //{
            //    From = "info@myanmarmedicalcouncil.org.mm",
            //    To = obj.Email,
            //    ViewName = "RenewalConfirmationEmailInfo",
            //    Subject = "Confirmation of Renewal Application",
            //    Accesstime = obj.Accesstime,
            //    Name = obj.Name,
            //    Code = obj.Code,
            //    CurrentAddress = obj.CurrentAddress,
            //    Degree = obj.Degree,
            //    Email = obj.Email,
            //    GraduationYear = obj.GraduationYear,
            //    Township = obj.Township,
            //    StateDivision = obj.StateDivision,
            //    NRC = obj.NRC,
            //    LicenseNo = obj.LicenseNo,
            //    PostalService = obj.PostalService,
            //    Phone = obj.Phone


            //}).SendAsync();
        }
        public ActionResult Index()
        {
            ViewBag.navInfo = "nav_renewal";
            return View();
        }

        //public ActionResult Confrim(string button, tbRenewalPractitionerApplication model)
        public ActionResult Confrim(string button)
        {
            //if (button == "edit")
            //{
            //    var obj = _renewalRepo.Query(a => a.ID == model.ID && a.Source == "ONLINE" && a.IsDeleted != true).FirstOrDefault();
            //    return PartialView("_Edit", obj);
            //}
            //else
            //{
                //tbRenewalPractitionerApplication result;
                //var obj = _renewalRepo.Query(a => a.ID == model.ID && a.Source == "ONLINE" && a.IsDeleted != true).FirstOrDefault();
                //if (obj != null)
                //{
                //    obj.Status = "CONFIRMED";
                //    result = _renewalRepo.UpdateComplete(model, obj);
                //    SendEmail(obj);
                //    return PartialView("_View", result);
                //}
                return Json("Error!",JsonRequestBehavior.AllowGet);

           // }
        }
        [HttpPost]
        //public ActionResult Edit(tbRenewalPractitionerApplication model)
        public ActionResult Edit()
        {
        //    if (ModelState.IsValid)
        //    {
        //        tbRenewalPractitionerApplication result;
        //        var obj = _renewalRepo.Query(a => a.LicenseNo == model.LicenseNo && a.IsDeleted != true).FirstOrDefault();
        //        if (obj != null)
        //        {
        //            if (obj.Status == "CONFIRMED")
        //            {
        //                return PartialView("_View", obj);
        //            }
        //            obj.Status = "APPLIED";
        //            obj.Accesstime = DateTime.Now;
        //            obj.CurrentAddress = model.CurrentAddress;
        //            obj.Degree = model.Degree;
        //            obj.Email = model.Email;
        //            obj.GraduationYear = model.GraduationYear;
        //            obj.LicenseNo = model.LicenseNo;
        //            obj.Name = model.Name;
        //            obj.NRC = model.NRC;
        //            obj.Occupation = model.Occupation;
        //            obj.Phone = model.Phone;
        //            obj.Source = model.Source;
        //            obj.StateDivision = model.StateDivision;
        //            obj.Township = model.Township;
        //            obj.Source = "ONLINE";
        //            result = _renewalRepo.UpdateComplete(model, obj);
        //        }
        //        else
        //        {
        //            int lgvalue = 0;
        //            if (_renewalRepo.Query(a => a.IsDeleted != true).Select(a => a.ID).Count() > 0)
        //            {
        //                lgvalue = _renewalRepo.Query(a => a.IsDeleted != true).Select(a => a.CodeIndex ?? 0).Max() + 1;
                        
        //            }
        //            else
        //            {
        //                lgvalue = 1;
        //            }
        //            model.Status = "APPLIED";
        //            model.CodeIndex = lgvalue;
        //            model.Code = "RN-".getCode(lgvalue, "000000");
        //            model.Accesstime = DateTime.Now;
        //            model.IsDeleted = false;
        //            model.Source = "ONLINE";
        //            result = _renewalRepo.InsertReturn(model);
        //        }
                
        //        if (result != null)
        //        {
        //            return PartialView("_Confirm", result);
        //        }
        //        else
        //        {
        //            return Json("Error!", JsonRequestBehavior.AllowGet);
        //        }
        //    }
            return Json("Error!", JsonRequestBehavior.AllowGet);
        }

    }
}

MMCWeb/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Admin Panel - @ViewBag.Title</title>
    
    <!-- Global stylesheets -->
    @*<link href="https://fonts.googleapis.com/css?family=Roboto:400,300,100,500,700,900" rel="stylesheet" type="text/css">*@
    @*<link href="~/themes/assets/css/icons/icomoon/styles.css" rel="stylesheet" type="text/css">
    <link href="~/themes/assets/css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="~/themes/assets/css/core.min.css" rel="stylesheet" type="text/css">
    <link href="~/themes/assets/css/components.min.css" rel="stylesheet" type="text/css">
    <link href="~/themes/assets/css/colors.min.css" rel="stylesheet" type="text/css">*@
    @Styles.Render("~/themes/assets/css/global")
    @Styles.Render("~/themes/assets/css/icons/icomoon/iconfont")

    @Styles.Render("~/themes/kendo/css/kendo")

    @Scripts.Render("~/bundles/modernizr")
    <!-- /global stylesheets -->

    @RenderSection("css", required: false)
</head>
<body class="navbar-top">

    <!-- Main navbar -->
    <div class="navbar navbar-default navbar-fixed-top header-highlight">
        <div class="navbar-header">
            <a class="navbar-brand" href="index.html"><span style="color:white;font-weight:bold;">MYANMAR MEDICAL COUNCIL</span></a>
            <ul class="nav navbar-nav pull-right visible-xs-block">
                <li><a data-toggle="collapse" data-target="#navbar-mobile"><i class="icon-tree5"></i></a></li>
                <li><a class="sidebar-mobile-main-toggle"><i class="icon-paragraph-justify3"></i></a></li>
            </ul>
        </div>
        <div class="navbar-collapse collapse" id="navbar-mobile">
            <ul class="nav navbar-nav">
                <li><a class="sidebar-control sidebar-main-toggle hidden-xs"><i class="icon-paragraph-justify3"></i></a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                
                @if (User.Identity.IsAuthenticated)
                {
                    <li class="dropdown dropdown-user">
                        <a class="dropdown-toggle" data-toggle="dropdown">
                            <i class="icon-cog5"></i>
                            <span>@User.Identity.Name</span>
                            <i class="caret"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-right">
                            <li><a href="@Url.Action("LogOut","Account")"><i class="icon-switch2"></i> Logout</a></li>
                        </ul>
                    </li>
                }
                
            </ul>
        </div>
    </div>
    <!-- /main navbar -->
    <!-- Page container -->
    <div class="page-container">
        <!-- Page content -->
        <div class="page-content">
            <!-- Main sidebar -->
            <div class="sidebar sidebar-main sidebar-fixed">
                <div class="sidebar-content">
                    <!-- User menu -->
                    @*<div class="sidebar-user">
                        <div class="category-content">
                            <div class="media">
                                <a href="#" class="media-left">
                                    <img src="@Url.Content("~/themes/assets/images/placeholder.jpg")" class="img-circle img-sm" alt="">
                                </a>
                                <div class="media-body">
                                    <span class="media-heading text-semibold">Victoria Baker</span>
                                    <div class="text-size-mini text-muted">
                                        <i class="icon-pin text-size-small"></i> &nbsp;Santa Ana, CA
                                    </div>
                                </div>
                                <div class="media-right media-middle">
                                    <ul class="icons-list">
                                        <li>
                                            <a href="#"><i class="icon-cog3"></i></a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>*@
                    <!-- /user menu -->
                    
                    @Html.Partial("_AdminSidebarPartial")

                </div>
            </div>
            <!-- /main sidebar -->
            <!-- Main content -->
            <div class="content-wrapper">
                @RenderSection("pageHeader", required: false)
                <!-- Content area -->
                <div class="content">
                    
                    @RenderBody()

                    <!-- Footer -->
                    @*<div class="footer text-muted">
                        &copy; 2015. <a href="#">Limitless Web App Kit</a> by <a href="http://themeforest.net/user/Kopyov" target="_blank">Eugene Kopyov</a>
                    </div>*@
                    <!-- /footer -->
                </div>
                <!-- /content area -->
            </div>
            <!-- /main content -->
        </div>
        <!-- /page content -->
    </div>
    <!-- /page container -->


    


    <!-- Core JS files -->
    @*<script type="text/javascript" src="~/themes/assets/js/plugins/loaders/pace.min.js"></script>*@
    @*<script type="text/javascript" src="~/themes/assets/js/core/libraries/jquery.min.js"></script>
    <script type="text/javascript" src="~/themes/assets/js/core/libraries/bootstrap.min.js"></script>
    <script type="text/javascript" src="~/themes/assets/js/plugins/loaders/blockui.min.js"></script>*@
    <!-- /core JS files -->

    <!-- Theme JS files -->
    @*<script type="text/javascript" src="~/themes/assets/js/plugins/ui/nicescroll.min.js"></script>
    <script type="text/javascript" src="~/themes/assets/js/core/app.js"></script>
    <script type="text/javascript" src="~/themes/assets/js/pages/layout_fixed_custom.js"></script>*@
    <!-- /theme JS files -->

    @Scripts.Render("~/bundles/jsrequire")
    
    @Scripts.Render("~/bundles/kendojs")

    @RenderSection("scripts", required: false)
</body>
</html>

MMCWeb/Views/Shared/_AdminSidebarPartial.cshtml
<!-- Main navigation -->
<div class="sidebar-category sidebar-category-visible">
    <div class="category-content no-padding">
        <ul class="navigation navigation-main navigation-accordion">
            <!-- Main -->
            <li class="navigation-header"><span>Admin Panel</span></li>

            @*@if (ViewBag.Title == "Admin Dashboard")
            {
                <li class="active"><a href="@Url.Action("Index")"><i class="icon-home4"></i> <span>Dashboard</span></a></li>
            }
            else
            {
                <li><a href="@Url.Action("Index")"><i class="icon-home4"></i> <span>Dashboard</span></a></li>
            }*@

            @if (ViewBag.Title == "Articles")
            {
                <li class="active"><a href="@Url.Action("Articles")"><i class="icon-list"></i> <span>Articles</span></a></li>
            }
            else
            {
                <li><a href="@Url.Action("Articles")"><i class="icon-list"></i> <span>Articles</span></a></li>
            }

            @if (ViewBag.Title == "Accounts")
            {
                <li class="active"><a href="@Url.Action("Accounts")"><i class="icon-user"></i> <span>Accounts</span></a></li>
            }
            else
            {
                <li><a href="@Url.Action("Accounts")"><i class="icon-user"></i> <span>Accounts</span></a></li>
            }

            <!-- /main -->
        </ul>
    </div>
</div>
<!-- /main navigation -->

MMCWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags always come first -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>@ViewBag.Title</title>

    <!--Fonts-->

    <link href='https://fonts.googleapis.com/css?family=Karla:400,400italic,700italic,700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Lora:400,400italic,700,700italic' rel='stylesheet' type='text/css'>

    <!--Bootstrap-->

    <link rel="stylesheet" href="~/Content/css/bootstrap.css">
    <link rel="stylesheet" href="~/Content/css/bootstrap-theme.min.css">
    <!--Bootstrap Select-->
    <link rel="stylesheet" href="~/Content/vendors/bootstrap-select/css/bootstrap-select.min.css">
    <!--Font Awesome-->
    <link rel="stylesheet" href="~/Content/css/font-awesome.min.css">
    <!--Owl Carousel-->
    <link rel="stylesheet" href="~/Content/vendors/owl.carousel/owl.carousel.css">
    <!--Magnific Popup-->
    <link rel="stylesheet" href="~/Content/vendors/magnific-popup/magnific-popup.css">

    <!--Theme Styles-->
    <link rel="stylesheet" href="~/Content/css/custom-style.css">
    <link rel="stylesheet" href="~/Content/css/style.css">
    <link rel="stylesheet" href="~/Content/css/theme.css">

   @RenderSection("head", required: false)
</head>


<body>
     @Html.Partial("_navigation")
     @RenderBody()
  
    
    <script src="~/Content/js/jquery-2.1.4.min.js"></script>
    <script src="~/Content/js/bootstrap.min.js"></script>
    <!--Bootstrap Select-->
    <script src="~/Content/vendors/bootstrap-select/js/bootstrap-select.min.js"></script>
    <!--Magnific Popup-->
    <script src="~/Content/vendors/magnific-popup/jquery.magnific-popup.min.js"></script>
    <!--Owl Carousel-->
    <script src="~/Content/vendors/owl.carousel/owl.carousel.min.js"></script>
    <!--CounterUp-->
    <script src="~/Content/vendors/couterup/jquery.counterup.min.js"></script>
    <!--WayPoints-->
    <script src="~/Content/vendors/waypoint/waypoints.min.js"></script>
    <script src="~/Content/js/theme.js"></script>

    @RenderSection("scripts", required: false)
    <script type="text/javascript">
    var navInfo = '@ViewBag.navInfo';
    
    var navIndex = $('#nav_home');
    var navAbout = $('#nav_about');
    var navInformation = $('#nav_information');
    var navEducation = $('#nav_med_education');
    var navReport = $('#nav_report');
    var navLegislation = $('#nav_legislation');
    var navNews = $('#nav_news');
    var navContact = $('#nav_contactus');
    $(function () {

        resetNavigation();
        $('#' + navInfo).addClass('active');
    });
    function resetNavigation()
    {
        navLegislation.removeClass('active');
        navIndex.removeClass('active');
        navAbout.removeClass('active');
        navInformation.removeClass('active');
        navEducation.removeClass('active');
        navReport.removeClass('active');
        navNews.removeClass('active');
        navContact.removeClass('active');
    }
    </script>


</body>

</html>

MMCWeb/Views/Shared/_footer.cshtml
<footer class="row foooter footer2">
    <div class="container">
        <div class="row footer_sidebar">
            <div class="widget widget-about col-sm-4 col-md-4">
                <h5 class="widget-title">about Myanmar Medical Council</h5>
                <p>Myanmar Medical Council, as it was known then, was formed under the Burma Medical Council Act, 1957. This Act was subsequently repealed and the Myanmar Medical Council Law was drafted and came into force on January 14, 2000.</p>
                <a asp-controller="Home" asp-action="About" target="_blank" class="btn-primary btn-outline white">Learn more</a>
            </div>
            <div class="widget widget-recent-tweets col-sm-4 col-md-4">
                <h5 class="widget-title">recent Facebook Posts</h5>
                <div class="tweet m0">
                    <p>
                        Please visit our official facebook page now.<br>
                      
                    </p>
                </div>
                <a href="https://www.facebook.com/myanmarmedicalcouncil/" target="_blank" class="btn btn-primary btn-outline white">Visit fb page now</a>
            </div>
            <div class="widget widget-recent-posts col-sm-4 col-md-4">
                <h5 class="widget-title">recent posts</h5>
                <ul class="nav recent-posts">
                    <li><a href="#">Online direct application for medical practitioner licence will be available soon.</a></li>
                </ul>
            </div>


        </div>
    </div>

    <div class="row copyright_area m0">
        <div class="container">
            <div class="copy_inner row">
                <div class="col-sm-8 copyright_text">Copyright 2016. All Rights Reserved by <a href="#">Myanmar Medical Council</a>. Designed by <a href="#">Xbiz and Inspiration Co.,Ltd</a>.</div>
                <div class="col-sm-4 footer-nav">
                    <ul class="nav">
                        <li><a href="#">Terms of Use</a></li>
                        <li><a href="#">Privacy Policy</a></li>
                        <li><a href="#">Desclaimer</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</footer>

MMCWeb/Views/Shared/_navigation.cshtml
<header class="row header1" style="padding:10px 0 0px 0;">

    <div class="container">
        <div class="logo pull-left">
            <img src="~/Content/images/logo.png" style="width:50px;position:relative;top:-10px;" />

        </div>
        
        <div class="pull-right emergency-contact">
            <div class="pull-left">
                <span><i class="fa fa-envelope-o"></i></span>
                <div class="infos_col">
                    <h6>email us at</h6>
                    <a href="mailto:info@myanmarmedicalcouncil.org"><h5>info@myanmarmedicalcouncil.org.mm</h5></a>
                </div>
            </div>
            <div class="pull-left">
                <span class="rotate"><i class="fa fa-phone"></i></span>
                <div class="infos_col">
                    <h6>call us now</h6>
                    <h4>+95-9-456844445</h4>
                </div>
            </div>
        </div>
    </div>
</header>
<nav class="navbar navbar-default navbar-static-top navbar2">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#mainNav" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse" id="mainNav">
            <ul class="nav navbar-nav">
                <li class="dropdown active" id="nav_home">
                    <a href="/Home/Index" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Home</a>
                    <ul class="dropdown-menu">
                        <li><a href="@Url.Action("Index", "Home")">Introduction</a></li>
                        <li><a href="@Url.Action("About", "Home")">About us</a></li>
                        <li><a href="@Url.Action("Setup", "Home")">Formation</a></li>


                    </ul>
                </li>
                <li id="nav_news"><a href="~/Articles/Index">News and Articles</a></li>
                @*<li class="dropdown" id="nav_med_education">
                    <a href="@Url.Action("Index", "Education")" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Medical Education</a>
                    <ul class="dropdown-menu">
                        <li><a href="@Url.Action("Accreditation", "Education")">Recognition of Postgraduate Diplomas and Degrees (Local and International)</a></li>
                        <li><a href="@Url.Action("Index", "Education")">List of Medical Universities and recognized medical qualifications</a></li>
                        @*<li><a asp-controller="Education" asp-action="Accreditation">Medical Accreditation Process</a></li>
                        <li><a asp-controller="Education" asp-action="EntryRequirement">Minimum Entry Requirements</a></li>
                    
                    </ul>
                </li>*@
                <li class="dropdown" id="nav_information">
                    <a href="@Url.Action("Index", "Information")" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Information</a>
                    <ul class="dropdown-menu">
                        <li><a href="@Url.Action("Registration", "Information")">Medical Practitioner Registration</a></li>
                        <li><a href="@Url.Action("Licencing", "Information")">Medical Practitioner licencing</a></li>
                        @*<li><a asp-controller="Information" asp-action="Goodstanding">Issuance of Certificate of Good Standing</a></li>
                        <li><a asp-controller="Information" asp-action="Arbitration">Arbitration and Dispute resolution</a></li>
                        <li><a asp-controller="Information" asp-action="Relationship">International Relations and Cooperation</a></li>*@
                    </ul>
                </li>
                <li class="dropdown" id="nav_application">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Application</a>
                    <ul class="dropdown-menu">
                        @*<li><a href="@Url.Action("New", "Application")">New Practitioner Application</a></li>*@
                        <li><a href="@Url.Action("Index", "RenewalApplication")">Renewal of Medical Practitioner Licence</a></li>
                    </ul>

                </li>
                <li class="dropdown" id="nav_legislation">
                    <a href="~/Legislation/Index">Legislation and Regulation</a>
                    
                </li>
          

                <li id="nav_contact"><a href="~/Contact/Index">contact</a></li>
            </ul>
            <ul class="nav social_navbar navbar-right">
                <li><a href="https://www.facebook.com/myanmarmedicalcouncil/" target="_blank"><i class="fa fa-facebook"></i></a></li>
                <li><a href="/Account/Login" target="_blank"><i class="fa fa-lock"></i></a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-search"></i></a>
                    <ul class="dropdown-menu">
                        <li>
                            <form action="#" method="get" role="form" class="search_form">
                                <input type="search" class="form-control" placeholder="Type and press enter">
                            </form>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>