MMCWebAdmin/Controllers/EducationHistoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Data.Models;
using Infra.Helper;

namespace DMAHR.Controllers
{
    public class EducationHistoryController : Controller
    {
        // GET: EducationHistory
        public async Task<ActionResult> Index(int Id)
        {
            ViewBag.PersonalId = Id;
            Personal result = await PersonalApiRequestHelper.GetPersonal(Id);
            //if (result == null)
            //{
            //    return PartialView("_NoEduHistory");
            //}
            //else
            //{
            //    return View(result);
            //}

            return View(result);
        }


        public async Task<ActionResult> GetHistory(int id)
        {
            EduHistory result = await EduHistoryApiRequestHelper.GetEduHistory(id);
            if(result !=null)
            {
                return PartialView("_Detail", result);
            }
            else
            {
                //return PartialView("_Detail", result);
                return PartialView("_NoEduHistory");
            }
          


        }

        public async Task<ActionResult> UpsertEducation(string FormType,int Id)
        {
            EduHistory eduHistory = new EduHistory();
            if(FormType == "Add")
            {
                eduHistory.PersonalID = Id;
                return PartialView("_Form",eduHistory);
            }
            else
            {
                eduHistory = await EduHistoryApiRequestHelper.GetEduHistoryId(Id);
                return PartialView("_Form", eduHistory);
            }
        }
        public async Task<ActionResult> UpsertEduHistory(EduHistory educationdata)
        {
            EduHistory result = await EduHistoryApiRequestHelper.UpsertEduHistory(educationdata);
            if (result != null)
            {
                return Json("Success", JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json("Fail", JsonRequestBehavior.AllowGet);
            }
        }


    }
}

MMCWebAdmin/Controllers/JobHistoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DMAHR.Controllers
{
    public class JobHistoryController : Controller
    {
        // GET: JobHistory
        public ActionResult Index(int Id)
        {
            ViewBag.PersonalId = Id;
            return View();
        }
    }
}

MMCWebAdmin/Controllers/PersonalDetailController.cs
using Data.Models;
using Data.ViewModels;
using Infra.Helper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace DMAHR.Controllers
{
    public class PersonalDetailController : Controller
    {
        // GET: PersonalDetail
        public ActionResult Index(int id)
        {
            ViewBag.PersonalId = id;
            return View();
        }

       
        public async Task<ActionResult> GetPersonalByID(string FormType, int id)
        {
           
            PersonalData result = await PersonalApiRequestHelper.GetPersonalById(id);

            return PartialView("_Detail", result);
        }

      

        public async Task<ActionResult> PersonalForm(string FormType, int id)
        {
            PersonalData result = new PersonalData();
            if(FormType == "Add")
            {
                return PartialView("_Form", result);
            }
            else
            {
                 result = await PersonalApiRequestHelper.GetPersonalById(id);

                return PartialView("_Form", result);
            }
        
        }
        [HttpPost]
        public async Task<ActionResult> UpsertPersonal(PersonalData personaldata)
        {

            Personal personal = new Personal();
            personal = personaldata.personalDivisionSection.persoanl;
            Personal result = await PersonalDetailApiRequestHelper.UpsertPersonal(personal);

            
             if (result != null)
            {
               
                return Json("Success", JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json("Fail", JsonRequestBehavior.AllowGet);
            }
        }


    }
}

MMCWebAdmin/Views/EducationHistory/Index.cshtml
@model Data.Models.Personal

@section head{
    <link href="~/Content/bootstrapValidator.css" rel="stylesheet" />
}

<div class="page-header">
    <div class="page-header-content">
        <div class="page-title">
            <h5>
                <i class="icon-arrow-left52 position-left"></i>
                <span class="text-semibold">EducationHistory Detail</span>
                <small>Admin Panel</small>
            </h5>
            <a class="heading-elements-toggle"><i class="icon-more"></i></a>
        </div>
    </div>
    @*<div class="container-fluid">

        <div class="content" id="ListResult" style="width:100%">
            <h3>Loading...</h3>
        </div>
    </div>*@
</div>





<div class="panel panel-default" id="panel_@Model.PersonalID">


    <div class="panel-heading" style="padding-top:0px !important">
        <div class="panel-title">
            <div class="media-left media-middle">

                <img style="max-height:none;" src="~/Images/doctor.png" class="img-circle img-responsive" alt="">
            </div>
            <div class="media-body">
                <div><h6><a data-toggle="collapse" data-parent="#accordion-control" href="#accordion-control-@Model.PersonalID" data-id="@Model.PersonalID" class="text-default text-semibold">@Model.Name &nbsp;</a></h6></div>
                <div class="text-size-large">
                    <span class="text-muted">@Model.CurrentRank</span>
                </div>

            </div>
            <div class="media-right media-middle">
                @*<ul class="icons-list">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-menu7"></i></a>
                        <ul class="dropdown-menu dropdown-menu-right">
                            <li><a onclick="EDIT(@Model.PersonalID, 'div_editForm', '@Url.Action("Edit", "Doctor")', 'editForm', 'modal_editForm')"><i class="icon-file-stats"></i> Edit</a></li>
                            <li><a onclick="deleteEntity(@Model.PersonalID)"><i class="icon-trash"></i> Delete</a></li>

                            <li class="divider"></li>
                            <li><a onclick="addquali(this)" data-id="@Model.PersonalID" data-name="@Model.Name"><i class="icon-gear"></i> Add Qualification</a></li>
                        </ul> 
                    </li>
                </ul>*@
            </div>


        </div>
    </div>
    <div id="accordion-control-@Model.PersonalID" class="panel-collapse collapse">
        <div id="qualifordoctor_@Model.PersonalID"></div>
    </div>
</div>



<div id="myModal" class="modal fade">
    @*<div class="modal-dialog modal-full">*@
    <div class="modal-dialog">
        <div class="modal-content">
            <div id="EducationHistory">
            </div>
        </div>
    </div>
</div>





    <div id="div-Education">
        @Html.Partial("_Detail", new EduHistory())
    </div>

    @*@Html.Partial("_NoEduHistory")*@

     @section Scripts{

        <script src="~/Scripts/bootstrap-datepicker.js"></script>
        <script src="~/Scripts/sweetalert.min.js"></script>
        <script src="~/Scripts/CRUD.js"></script>
        @Scripts.Render("~/bundles/validation")
        <script type="text/javascript">
            var Id=@ViewBag.PersonalId;

            $(function (){

                LoadMainList();
            });

            function LoadMainList(){
                $.ajax({
                    url:'@Url.Action("GetHistory", "EducationHistory")',
                    data:{Id:Id},
                    beforeSend:function(){

                    },
                    success:function(result){
                        
                            $("#div-Education").empty().append(result);
                        
                        //else{
                        //    $("#div-EduHistory").empty().append(result);
                        //}


                    },
                    complete:function(){

                    }
                })

            }
            

            function addEduHistory(){
                EducationForm("Add",Id);
            }

            function EditEduHistory(e){
                alert("Hello");
                var ID=$(e).attr('data-EduId')
                alert(ID);
                EducationForm("Edit",ID);
            }

           
            function EducationForm(FormType,Id)
            {
                $.ajax({
                    url:'@Url.Action("UpsertEducation","EducationHistory")',
                    data:{FormType:FormType,Id:Id},
                    beforeSend:function(){

                    },
                    success:function(result){
                        $("#EducationHistory").empty().append(result)
                    },
                    complete:function(){
                        $("#myModal").modal('show');
                        $('.datepicker').datepicker();


                        @*$("EducationForm").submit(function (e){
                            e.preventDefault();
                            $.ajax({
                                cache:false,
                                url:'@Url.Action("UpsertEduHistory","EducationHistory")',
                                type:"Post",
                                
                                data:$(this).serialize(),
                              
                                beforeSend:function(){
                                    $('.btn').prop("disabled", true);
                                },
                                complete:function(){

                                },
                                success:function(){
                                    $("myModal").modal('hide');
                                    $('.btn').prop("disabled", true);

                                }


                            })
                        });*@



                        $('#EducationForm').submit(function (e) {
                            e.preventDefault();
                            $.ajax({
                                cache: false,
                                url: '@Url.Action("UpsertEduHistory", "EducationHistory")',
                                type: "Post",
                                data: $(this).serialize(),
                                beforeSend: function () {
                                    $('.btn').prop("disabled", true);
                                },
                                success: function (myData) {
                               
                                },
                                complete: function () {
                                    $('#myModal').modal('hide');
                                    $('.btn').prop("disabled", false);
                                    LoadMainList();
                                }
                            });


                        });


              
                    }
                })
              
            }

        </script>
    }

MMCWebAdmin/Views/EducationHistory/_Detail.cshtml
@model Data.Models.EduHistory





<div style="margin-left:10px">
    <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
        <li class="nav-item"><a href="#home" onclick="location.href='@Url.Action("Index", "PersonalDetail")?Id='+@Model.PersonalID" role="tab" data-toggle="tab">Personal</a></li>
      
        <li class="nav-item active"><a href="#educationHistory"  role="tab" data-toggle="tab">Education History</a></li>
        <li><a href="#history"  role="tab" onclick="location.href='@Url.Action("Index","JobHistory")?Id='+@Model.PersonalID" data-toggle="tab">JobHistory</a></li>
        <li class="dropdown" style="float:right">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-menu7"></i></a>
            <ul class="dropdown-menu dropdown-menu-right">

                @*<li onclick="addEduHistory()"><a><i class="icon-file-stats"></i> Add</a></li>*@
                <li><a data-EduId="@Model.EduHistoryID" onclick="EditEduHistory(this)"><i class="icon-file-stats"></i> Edit</a></li>
             
                <li><a><i class="icon-trash"></i> Delete</a></li>


            </ul>
        </li>
    </ul>

    <hr />
    <div class="tab-content" style="margin-left:10px;">

        <div class="tab-pane fade" id="home">
          
        </div>

        <div class="tab-pane fade in active" id="educationHistory">
            <div class="form-group">
                <label class="col-sm-3">SchoolOrCollegueOrUniversity</label>
                @Html.TextBoxFor(a => a.SchoolOrCollegueOrUniversity)
              
            </div>
            <div class="form-group">
                <label class="col-sm-3">Education</label>
                @Html.TextBoxFor(a => a.Education)
            </div>
            <div class="form-group">
                <label class="col-sm-3">FromDate</label>
                @Html.TextBoxFor(a => a.FromDate, "{0:dd/MM/yyyy}")
            </div>
            <div class="form-group">
                <label class="col-sm-3">ToDate</label>
                @Html.TextBoxFor(a => a.ToDate, "{0:dd/MM/yyyy}")
            </div>
            <div class="form-group">
                <label class="col-sm-3">SchoolAddress</label>
                @Html.TextBoxFor(a => a.SchoolAddress)
            </div>
            <div class="form-group">
                <label class="col-sm-3">Rank</label>
                @Html.TextBoxFor(a => a.Rank)
            </div>
            <div class="form-group">
                <label class="col-sm-3">LastSchool</label>
                @Html.TextBoxFor(a => a.LastSchool)
            </div>
            <div class="form-group">
                <label class="col-sm-3">StudentLifeActivity</label>
                @Html.TextBoxFor(a => a.StudentLifeActivity)
            </div>
        </div>

        <div class="tab-pane fade" id="history">
            <p>History Content : ...</p>
        </div>

      

    </div>



</div>

MMCWebAdmin/Views/EducationHistory/_Form.cshtml
@model Data.Models.EduHistory

@*@if(Model != null)*@

<div class="modal-header bg-primary">
    <button type="button" class="close" data-dismiss="modal">&times;</button>
    <h5 class="modal-title"><i class="icon-menu7"></i> &nbsp;EducationHistory Registration form</h5>
</div>
@using (Html.BeginForm("UpsertEduHistory", "EducationHistory", FormMethod.Post, new { id = "EducationForm", @class = "form-vertical form-validate-jquery" }))
{
    <div class="modal-body">
        <div class="alert alert-info alert-styled-left text-blue-800 content-group">
            <span class="text-semibold">Add Education History Data</span> @*Here is the form for registering new education history.*@
            <button type="button" class="close" data-dismiss="alert">×</button>
        </div>

        <div class="form-group">
            <label>PersonalID:</label>
            <input type="text" name="PersonalID" value="@Model.PersonalID" class="form-control" />
        </div>

       <div class="form-group">
            <label>SchoolOrCollegueOrUniversity:</label>
            <input type="text" name="SchoolOrCollegueOrUniversity" value="@Model.SchoolOrCollegueOrUniversity" class="form-control">
        </div>


        <div class="form-group">
            <label>Education:</label>
            <input type="text" name="Education" value="@Model.Education" class="form-control">
        </div>

        <div class="form-group">
            <label for="usr">FromDate:</label>
            <input class="form-control datepicker" name="FromDate" value="@Model.FromDate"  type="text" />

        </div>

        <div class="form-group">
            <label for="usr">ToDate:</label>
            <input class="form-control datepicker" name="ToDate" value="@Model.ToDate" type="text" autocomplete="off" />

        </div>

        <div class="form-group">
            <label for="usr">School Address:</label>
            <input type="text" class="form-control" value="@Model.SchoolAddress" name="SchoolAddress">
        </div>

        <div class="form-group">
            <label for="usr">Rank:</label>
            <input type="text" class="form-control" value="@Model.Rank" name="Rank">
        </div>
        <div class="form-group">
            <label for="usr">Last School:</label>
            <input type="text" class="form-control" value="@Model.LastSchool" name="LastSchool">
        </div>
        <div class="form-group">
            <label for="usr">Student Life Activity:</label>
            <input type="text" class="form-control" value="@Model.StudentLifeActivity" name="StudentLifeActivity">
        </div>

        <input type="hidden" value="@Model.EduHistoryID" name="EduHistoryID"/>
        @*<div class="form-group">
            <label>Education:</label>
            <input type="text" name="Education" value="@Model.Education" class="form-control">
        </div>*@


    @*<div class="form-group">
        <label for="usr">FromDate:</label>
        <input class="form-control datepicker" name="FromDate" type="text" />
       
    </div>*@
    @*<div class="form-group">
        <label for="usr">ToDate:</label>

        <input class="form-control datepicker" name="ToDate" value="@Model.ToDate" type="text" />
    </div>
    <div class="form-group">
        <label for="usr">School Address:</label>
        <input type="text" class="form-control" value="@Model.SchoolAddress" name="SchoolAddress" >
    </div>
    <div class="form-group">
        <label for="usr">Rank:</label>
        <input type="text" class="form-control" value="@Model.Rank" name="Rank" >
    </div>
    <div class="form-group">
        <label for="usr">Last School:</label>
        <input type="text" class="form-control" value="@Model.LastSchool" name="LastSchool">
    </div>
    <div class="form-group">
        <label for="usr">Student Life Activity:</label>
        <input type="text" class="form-control" value="@Model.StudentLifeActivity" name="StudentLifeActivity" >
    </div>*@

     

        
    </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-link" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Submit form</button>
        </div>
}
 

MMCWebAdmin/Views/EducationHistory/_NoEduHistory.cshtml
<div style="margin-left:10px">
    <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
        <li class="nav-item"><a href="#home"  role="tab" data-toggle="tab">Personal</a></li>

        <li class="nav-item active"><a href="#educationHistory" role="tab" data-toggle="tab">Education History</a></li>
        <li><a href="#history" role="tab" data-toggle="tab">History</a></li>
        <li class="dropdown" style="float:right">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-menu7"></i></a>
            <ul class="dropdown-menu dropdown-menu-right">

                <li onclick="addEduHistory()"><a ><i class="icon-file-stats"></i> Add</a></li>
                <li><a><i class="icon-file-stats"></i> Edit</a></li>
                <li><a><i class="icon-trash"></i> Delete</a></li>


            </ul>
        </li>

    </ul>

    <hr />
    <div class="tab-content" style="margin-left:10px;">

        <div class="tab-pane fade" id="home">
            <h3>Personal</h3>
        </div>

        <div class="tab-pane fade in active" id="educationHistory">
            <h3>No Education Data</h3>
        </div>

        <div class="tab-pane fade" id="history">
            <p>No History Content : ...</p>
        </div>



    </div>



</div>